<?php

namespace ContainerZm18Vj1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getVite_EntrypointRendererService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'vite.entrypoint_renderer' shared service.
     *
     * @return \Pentatrion\ViteBundle\Asset\EntrypointRenderer
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/pentatrion/vite-bundle/src/Asset/EntrypointRenderer.php';

        return $container->services['vite.entrypoint_renderer'] = new \Pentatrion\ViteBundle\Asset\EntrypointRenderer(($container->services['vite.entrypoints_lookup'] ?? $container->load('getVite_EntrypointsLookupService')), ($container->services['vite.tag_renderer'] ?? $container->load('getVite_TagRendererService')));
    }
}
