<?php

namespace ContainerZm18Vj1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getVite_TagRendererService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'vite.tag_renderer' shared service.
     *
     * @return \Pentatrion\ViteBundle\Asset\TagRenderer
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/pentatrion/vite-bundle/src/Asset/TagRenderer.php';

        return $container->services['vite.tag_renderer'] = new \Pentatrion\ViteBundle\Asset\TagRenderer('default', $container->parameters['pentatrion_vite.builds']);
    }
}
