<?php

namespace ContainerZm18Vj1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getViteControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'Pentatrion\ViteBundle\Controller\ViteController' shared service.
     *
     * @return \Pentatrion\ViteBundle\Controller\ViteController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/pentatrion/vite-bundle/src/Controller/ViteController.php';

        return $container->services['Pentatrion\\ViteBundle\\Controller\\ViteController'] = new \Pentatrion\ViteBundle\Controller\ViteController('default', $container->parameters['pentatrion_vite.builds'], ($container->privates['http_client'] ?? $container->load('getHttpClientService')), ($container->services['vite.entrypoints_lookup'] ?? $container->load('getVite_EntrypointsLookupService')));
    }
}
