<?php

namespace ContainerZm18Vj1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getVite_EntrypointsLookupService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'vite.entrypoints_lookup' shared service.
     *
     * @return \Pentatrion\ViteBundle\Asset\EntrypointsLookup
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/pentatrion/vite-bundle/src/Asset/EntrypointsLookup.php';

        return $container->services['vite.entrypoints_lookup'] = new \Pentatrion\ViteBundle\Asset\EntrypointsLookup((\dirname(__DIR__, 4).'/public'), 'default', $container->parameters['pentatrion_vite.builds']);
    }
}
