<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZm18Vj1\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZm18Vj1/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZm18Vj1.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZm18Vj1\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerZm18Vj1\App_KernelDevDebugContainer([
    'container.build_hash' => 'Zm18Vj1',
    'container.build_id' => 'c0c53793',
    'container.build_time' => 1680460801,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZm18Vj1');
